<?php
/**
 * Title: Index template.
 *
 * Description: Defines content of default index template.
 *
 * Please do not edit this file. This file is part of the Annymo-wp Framework and all modifications
 * should be made in a child theme.
 *
 * @category Annymo-wp Framework
 * @package  Framework
 * @since    1.0
 * @author   MOSHIUR RAHMAN NIC
 * @license  http://www.opensource.org/licenses/gpl-license.php GPL v2.0 (or later)
 * @link     http://www.moshiur.info/
 */
 
get_header(); ?>

<?php do_action( 'bzbd_before_container' ); ?>
  
<?php do_action( 'bzbd_blog_content' ); ?>	

<?php do_action( 'bzbd_after_container'); ?>

<?php get_footer(); ?>
